# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kramdown/all/kramdown.rbi
#
# kramdown-2.4.0

module Kramdown
end
class Kramdown::Element
end
class Kramdown::Error < RuntimeError
end
module Kramdown::Parser
end
module Kramdown::Utils
end
module Kramdown::Utils::Configurable
end
module Kramdown::Converter
  extend Kramdown::Utils::Configurable
end
module Kramdown::Options
end
class Kramdown::Options::Boolean
end
class Kramdown::Document
end
class Kramdown::Converter::Base
end
module Kramdown::Utils::Html
end
class Kramdown::Parser::Base
end
module Kramdown::Utils::Entities
end
class Kramdown::Parser::Html < Kramdown::Parser::Base
  include Kramdown::Parser::Html::Parser
end
module Kramdown::Parser::Html::Constants
end
module Kramdown::Parser::Html::Parser
  include Kramdown::Parser::Html::Constants
end
class Kramdown::Parser::Html::ElementConverter
  include Kramdown::Parser::Html::Constants
  include Kramdown::Utils::Entities
end
class Kramdown::Converter::Html < Kramdown::Converter::Base
  include Kramdown::Parser::Html::Constants
  include Kramdown::Utils::Html
end
class Kramdown::Parser::Kramdown < Kramdown::Parser::Base
  include Kramdown
  include Kramdown::Parser::Html::Parser
end
