# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rbs/all/rbs.rbi
#
# rbs-2.8.2

module RBS
end
module RBS::MethodNameHelper
end
class RBS::BaseError < StandardError
end
class RBS::LoadingError < RBS::BaseError
end
class RBS::DefinitionError < RBS::BaseError
end
class RBS::ParsingError < RBS::BaseError
end
class RBS::InvalidTypeApplicationError < RBS::DefinitionError
end
class RBS::RecursiveAncestorError < RBS::DefinitionError
end
class RBS::NoTypeFoundError < RBS::BaseError
end
class RBS::NoSuperclassFoundError < RBS::DefinitionError
end
class RBS::InheritModuleError < RBS::DefinitionError
end
class RBS::NoSelfTypeFoundError < RBS::DefinitionError
end
class RBS::NoMixinFoundError < RBS::DefinitionError
end
class RBS::DuplicatedMethodDefinitionError < RBS::DefinitionError
end
class RBS::DuplicatedInterfaceMethodDefinitionError < RBS::DefinitionError
end
class RBS::UnknownMethodAliasError < RBS::DefinitionError
end
class RBS::SuperclassMismatchError < RBS::DefinitionError
end
class RBS::InvalidOverloadMethodError < RBS::DefinitionError
end
class RBS::GenericParameterMismatchError < RBS::LoadingError
end
class RBS::DuplicatedDeclarationError < RBS::LoadingError
end
class RBS::InvalidVarianceAnnotationError < RBS::DefinitionError
end
class RBS::RecursiveAliasDefinitionError < RBS::DefinitionError
end
class RBS::MixinClassError < RBS::DefinitionError
end
class RBS::RecursiveTypeAliasError < RBS::BaseError
end
class RBS::NonregularTypeAliasError < RBS::BaseError
end
class RBS::CyclicTypeParameterBound < RBS::BaseError
end
class RBS::Buffer
end
class RBS::Namespace
end
module Kernel
end
class RBS::TypeName
end
module RBS::Types
end
module RBS::Types::NoFreeVariables
end
module RBS::Types::NoSubst
end
module RBS::Types::NoTypeName
end
module RBS::Types::EmptyEachType
end
module RBS::Types::Bases
end
class RBS::Types::Bases::Base
  include RBS::Types::EmptyEachType
  include RBS::Types::NoFreeVariables
  include RBS::Types::NoSubst
  include RBS::Types::NoTypeName
end
class RBS::Types::Bases::Bool < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Void < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Any < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Nil < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Top < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Bottom < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Self < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Instance < RBS::Types::Bases::Base
end
class RBS::Types::Bases::Class < RBS::Types::Bases::Base
end
class RBS::Types::Variable
  include RBS::Types::EmptyEachType
  include RBS::Types::NoTypeName
end
class RBS::Types::ClassSingleton
  include RBS::Types::EmptyEachType
  include RBS::Types::NoFreeVariables
  include RBS::Types::NoSubst
end
module RBS::Types::Application
end
class RBS::Types::Interface
  include RBS::Types::Application
end
class RBS::Types::ClassInstance
  include RBS::Types::Application
end
class RBS::Types::Alias
  include RBS::Types::Application
end
class RBS::Types::Tuple
end
class RBS::Types::Record
end
class RBS::Types::Optional
end
class RBS::Types::Union
end
class RBS::Types::Intersection
end
class RBS::Types::Function
end
class RBS::Types::Function::Param
end
class RBS::Types::Block
end
module RBS::Types::SelfTypeBindingHelper
end
class RBS::Types::Proc
end
class RBS::Types::Literal
  include RBS::Types::EmptyEachType
  include RBS::Types::NoFreeVariables
  include RBS::Types::NoSubst
  include RBS::Types::NoTypeName
end
class RBS::MethodType
end
module RBS::AST
end
class RBS::AST::TypeParam
end
module RBS::AST::Declarations
end
class RBS::AST::Declarations::Base
end
module RBS::AST::Declarations::NestedDeclarationHelper
end
module RBS::AST::Declarations::MixinHelper
end
class RBS::AST::Declarations::Class < RBS::AST::Declarations::Base
  include RBS::AST::Declarations::MixinHelper
  include RBS::AST::Declarations::NestedDeclarationHelper
end
class RBS::AST::Declarations::Class::Super
end
class RBS::AST::Declarations::Module < RBS::AST::Declarations::Base
  include RBS::AST::Declarations::MixinHelper
  include RBS::AST::Declarations::NestedDeclarationHelper
end
class RBS::AST::Declarations::Module::Self
end
class RBS::AST::Declarations::Interface < RBS::AST::Declarations::Base
  include RBS::AST::Declarations::MixinHelper
end
class RBS::AST::Declarations::Alias < RBS::AST::Declarations::Base
end
class RBS::AST::Declarations::Constant < RBS::AST::Declarations::Base
end
class RBS::AST::Declarations::Global < RBS::AST::Declarations::Base
end
module RBS::AST::Members
end
class RBS::AST::Members::Base
end
class RBS::AST::Members::MethodDefinition < RBS::AST::Members::Base
end
module RBS::AST::Members::Var
end
class RBS::AST::Members::InstanceVariable < RBS::AST::Members::Base
  include RBS::AST::Members::Var
end
class RBS::AST::Members::ClassInstanceVariable < RBS::AST::Members::Base
  include RBS::AST::Members::Var
end
class RBS::AST::Members::ClassVariable < RBS::AST::Members::Base
  include RBS::AST::Members::Var
end
module RBS::AST::Members::Mixin
end
class RBS::AST::Members::Include < RBS::AST::Members::Base
  include RBS::AST::Members::Mixin
end
class RBS::AST::Members::Extend < RBS::AST::Members::Base
  include RBS::AST::Members::Mixin
end
class RBS::AST::Members::Prepend < RBS::AST::Members::Base
  include RBS::AST::Members::Mixin
end
module RBS::AST::Members::Attribute
end
class RBS::AST::Members::AttrReader < RBS::AST::Members::Base
  include RBS::AST::Members::Attribute
end
class RBS::AST::Members::AttrAccessor < RBS::AST::Members::Base
  include RBS::AST::Members::Attribute
end
class RBS::AST::Members::AttrWriter < RBS::AST::Members::Base
  include RBS::AST::Members::Attribute
end
module RBS::AST::Members::LocationOnly
end
class RBS::AST::Members::Public < RBS::AST::Members::Base
  include RBS::AST::Members::LocationOnly
end
class RBS::AST::Members::Private < RBS::AST::Members::Base
  include RBS::AST::Members::LocationOnly
end
class RBS::AST::Members::Alias < RBS::AST::Members::Base
end
class RBS::AST::Annotation
end
class RBS::Environment
end
module RBS::Environment::ContextUtil
end
class RBS::Environment::MultiEntry
end
class RBS::Environment::MultiEntry::D < Struct
  include RBS::Environment::ContextUtil
end
class RBS::Environment::ModuleEntry < RBS::Environment::MultiEntry
end
class RBS::Environment::ClassEntry < RBS::Environment::MultiEntry
end
class RBS::Environment::SingleEntry
  include RBS::Environment::ContextUtil
end
class RBS::EnvironmentLoader
end
class RBS::EnvironmentLoader::UnknownLibraryError < StandardError
end
module RBS::BuiltinNames
end
class RBS::BuiltinNames::Name
end
class RBS::Definition
end
class RBS::Definition::Variable
end
class RBS::Definition::Method
end
class RBS::Definition::Method::TypeDef
end
module RBS::Definition::Ancestor
end
class RBS::Definition::Ancestor::Instance
end
class RBS::Definition::Ancestor::Singleton
end
class RBS::Definition::InstanceAncestors
end
class RBS::Definition::SingletonAncestors
end
class RBS::DefinitionBuilder
end
class RBS::DefinitionBuilder::AncestorBuilder
end
class RBS::DefinitionBuilder::AncestorBuilder::OneAncestors
end
class RBS::DefinitionBuilder::MethodBuilder
end
class RBS::DefinitionBuilder::MethodBuilder::Methods
end
class RBS::DefinitionBuilder::MethodBuilder::Methods::Sorter
  include TSort
end
class RBS::VarianceCalculator
end
class RBS::VarianceCalculator::Result
end
class RBS::Substitution
end
class RBS::Constant
end
module RBS::Resolver
end
class RBS::Resolver::ConstantResolver
end
class RBS::Resolver::ConstantResolver::Table
end
class RBS::Resolver::TypeNameResolver
end
class RBS::ConstantTable
end
class RBS::AST::Comment
end
class RBS::Writer
end
module RBS::Prototype
end
module RBS::Prototype::Helpers
end
class RBS::Prototype::RBI
end
class RBS::Prototype::RB
  include RBS::Prototype::Helpers
end
class RBS::Prototype::Runtime
  include RBS::Prototype::Helpers
end
class RBS::TypeNameResolver
end
class RBS::EnvironmentWalker
  include TSort
end
class RBS::Vendorer
end
class RBS::Validator
end
class RBS::Factory
end
class RBS::Repository
end
class RBS::Repository::GemRBS
end
class RBS::AncestorGraph
end
class RBS::Locator
end
class RBS::TypeAliasDependency
end
class RBS::TypeAliasRegularity
end
class RBS::TypeAliasRegularity::Diagnostic
end
module RBS::Collection
end
module RBS::Collection::Sources
end
module RBS::Collection::Sources::Base
end
class RBS::Collection::Sources::Git
  include RBS::Collection::Sources::Base
end
class RBS::Collection::Sources::Git::CommandError < StandardError
end
class RBS::Collection::Sources::Stdlib
  extend Singleton::SingletonClassMethods
  include RBS::Collection::Sources::Base
  include Singleton
end
class RBS::Collection::Sources::Rubygems
  extend Singleton::SingletonClassMethods
  include RBS::Collection::Sources::Base
  include Singleton
end
class RBS::Collection::Config
end
class RBS::Collection::Config::CollectionNotAvailable < StandardError
end
class RBS::Collection::Config::LockfileGenerator
end
class RBS::Collection::Config::LockfileGenerator::GemfileLockMismatchError < StandardError
end
class RBS::Collection::Installer
end
class RBS::Collection::Cleaner
end
class RBS::Parser
end
class RBS::Location
end
