# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/reverse_markdown/all/reverse_markdown.rbi
#
# reverse_markdown-2.1.1

module ReverseMarkdown
end
class ReverseMarkdown::Error < StandardError
end
class ReverseMarkdown::UnknownTagError < ReverseMarkdown::Error
end
class ReverseMarkdown::InvalidConfigurationError < ReverseMarkdown::Error
end
class ReverseMarkdown::Cleaner
end
class ReverseMarkdown::Config
end
module ReverseMarkdown::Converters
end
class ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::A < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Blockquote < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Br < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Bypass < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Code < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Del < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Div < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Drop < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Details < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Em < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::FigCaption < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Figure < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::H < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Hr < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Ignore < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Img < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Li < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Ol < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::P < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::PassThrough < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Pre < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Strong < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Table < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Td < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Text < ReverseMarkdown::Converters::Base
end
class ReverseMarkdown::Converters::Tr < ReverseMarkdown::Converters::Base
end
