# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-capybara/all/rubocop-capybara.rbi
#
# rubocop-capybara-2.20.0

module RuboCop
end
module RuboCop::Cop
end
module RuboCop::Cop::Capybara
end
module RuboCop::Cop::Capybara::CapybaraHelp
end
class RuboCop::Cop::Capybara::CssAttributesParser
end
module RuboCop::Cop::Capybara::CssSelector
end
module RuboCop::Cop::Capybara::RSpec
end
class RuboCop::Cop::Capybara::RSpec::HaveSelector < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
module RuboCop::Cop::Capybara::RSpec::InflectedHelper
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::Capybara::RSpec::ExplicitHelper
  extend RuboCop::AST::NodePattern::Macros
end
class RuboCop::Cop::Capybara::RSpec::PredicateMatcher < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::Capybara::RSpec::ExplicitHelper
  include RuboCop::Cop::Capybara::RSpec::InflectedHelper
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Capybara::ClickLinkOrButtonStyle < RuboCop::Cop::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Capybara::CurrentPathExpectation < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Capybara::MatchStyle < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Capybara::NegationMatcher < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Capybara::RedundantWithinFind < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Capybara::SpecificActions < RuboCop::Cop::Base
end
class RuboCop::Cop::Capybara::SpecificFinders < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Capybara::SpecificMatcher < RuboCop::Cop::Base
end
class RuboCop::Cop::Capybara::VisibilityMatcher < RuboCop::Cop::Base
end
