# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-rspec/all/rubocop-rspec.rbi
#
# rubocop-rspec-2.26.1

module RuboCop
end
module RuboCop::RSpec
end
module RuboCop::RSpec::Inject
end
module RuboCop::RSpec::Language
  extend RuboCop::AST::NodePattern::Macros
  extend RuboCop::RSpec::Language::NodePattern
end
module RuboCop::RSpec::Language::NodePattern
end
module RuboCop::RSpec::Node
end
module RuboCop::RSpec::Version
end
class RuboCop::RSpec::Wording
end
module RuboCop::RSpec::Language::ExampleGroups
end
module RuboCop::RSpec::Language::Examples
end
module RuboCop::RSpec::Language::Expectations
end
module RuboCop::RSpec::Language::Helpers
end
module RuboCop::RSpec::Language::Hooks
end
module RuboCop::RSpec::Language::HookScopes
end
module RuboCop::RSpec::Language::Includes
end
module RuboCop::RSpec::Language::Runners
end
module RuboCop::RSpec::Language::SharedGroups
end
module RuboCop::RSpec::Language::Subjects
end
module RuboCop::RSpec::Language::ALL
end
module RuboCop::Cop
end
module RuboCop::Cop::RSpec
end
module RuboCop::Cop::RSpec::FileHelp
end
module RuboCop::Cop::RSpec::FinalEndLocation
end
module RuboCop::Cop::RSpec::InsideExampleGroup
end
module RuboCop::Cop::RSpec::LocationHelp
end
module RuboCop::Cop::RSpec::Metadata
  extend RuboCop::AST::NodePattern::Macros
  include RuboCop::RSpec::Language
end
module RuboCop::Cop::RSpec::Namespace
end
module RuboCop::Cop::RSpec::SkipOrPending
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::RSpec::TopLevelGroup
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::RSpec::Variable
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::RSpec::CommentsHelp
  include RuboCop::Cop::RSpec::FinalEndLocation
end
module RuboCop::Cop::RSpec::EmptyLineSeparation
  include RuboCop::Cop::RSpec::FinalEndLocation
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::Base < RuboCop::Cop::Base
  extend RuboCop::RSpec::Language::NodePattern
  include RuboCop::RSpec::Language
end
class RuboCop::RSpec::AlignLetBrace
  include RuboCop::Cop::Util
  include RuboCop::RSpec::Language
end
class RuboCop::RSpec::Concept
  extend RuboCop::AST::NodePattern::Macros
  extend RuboCop::RSpec::Language::NodePattern
  include RuboCop::RSpec::Language
end
module RuboCop::RSpec::Corrector
end
class RuboCop::RSpec::Corrector::MoveNode
  include RuboCop::Cop::RSpec::CommentsHelp
  include RuboCop::Cop::RSpec::FinalEndLocation
  include RuboCop::Cop::RangeHelp
end
class RuboCop::RSpec::Example < RuboCop::RSpec::Concept
end
class RuboCop::RSpec::ExampleGroup < RuboCop::RSpec::Concept
end
class RuboCop::RSpec::Hook < RuboCop::RSpec::Concept
end
module RuboCop::Cop::RSpec::Capybara
end
class RuboCop::Cop::RSpec::Capybara::FeatureMethods < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::InsideExampleGroup
end
module RuboCop::Cop::RSpec::FactoryBot
end
module RuboCop::Cop::RSpec::Rails
end
class RuboCop::Cop::RSpec::Rails::AvoidSetupHook < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::Rails::HaveHttpStatus < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::Rails::NegationBeValid < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::Rails::HttpStatus < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::Rails::HttpStatus::StyleCheckerBase
end
class RuboCop::Cop::RSpec::Rails::HttpStatus::SymbolicStyleChecker < RuboCop::Cop::RSpec::Rails::HttpStatus::StyleCheckerBase
end
class RuboCop::Cop::RSpec::Rails::HttpStatus::NumericStyleChecker < RuboCop::Cop::RSpec::Rails::HttpStatus::StyleCheckerBase
end
class RuboCop::Cop::RSpec::Rails::HttpStatus::BeStatusStyleChecker < RuboCop::Cop::RSpec::Rails::HttpStatus::StyleCheckerBase
end
class RuboCop::Cop::RSpec::Rails::InferredSpecType < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::Rails::MinitestAssertions < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::Rails::TravelAround < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::AlignLeftLetBrace < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::AlignRightLetBrace < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::AnyInstance < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::AroundBlock < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::Be < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::BeEmpty < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::BeEq < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::BeEql < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::BeNil < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::BeforeAfterAll < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::ChangeByZero < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ClassCheck < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::ContainExactly < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ContextMethod < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ContextWording < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::AllowedPattern
end
class RuboCop::Cop::RSpec::DescribeClass < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::DescribeMethod < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::DescribeSymbol < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::DescribedClass < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RSpec::Namespace
end
class RuboCop::Cop::RSpec::DescribedClassModuleWrapping < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::Dialect < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::MethodPreference
end
class RuboCop::Cop::RSpec::DuplicatedMetadata < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::Metadata
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::EmptyExampleGroup < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::EmptyHook < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::EmptyLineAfterExample < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::EmptyLineSeparation
end
class RuboCop::Cop::RSpec::EmptyLineAfterExampleGroup < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::EmptyLineSeparation
end
class RuboCop::Cop::RSpec::EmptyLineAfterFinalLet < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::EmptyLineSeparation
end
class RuboCop::Cop::RSpec::EmptyLineAfterHook < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RSpec::EmptyLineSeparation
end
class RuboCop::Cop::RSpec::EmptyLineAfterSubject < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::EmptyLineSeparation
  include RuboCop::Cop::RSpec::InsideExampleGroup
end
class RuboCop::Cop::RSpec::EmptyMetadata < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::Metadata
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::Eq < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::ExampleLength < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::CodeLength
end
class RuboCop::Cop::RSpec::ExampleWithoutDescription < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::ExampleWording < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ExcessiveDocstringSpacing < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ExpectActual < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ExpectChange < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::ExpectInHook < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::ExpectOutput < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::FilePath < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::Namespace
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::Focus < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::HookArgument < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::HooksBeforeExamples < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::IdenticalEqualityAssertion < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::ImplicitBlockExpectation < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::ImplicitExpect < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::ImplicitSubject < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::IndexedLet < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::AllowedIdentifiers
  include RuboCop::Cop::AllowedPattern
end
class RuboCop::Cop::RSpec::InstanceSpy < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::InstanceVariable < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::ItBehavesLike < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::IteratedExpectation < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::LeadingSubject < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::InsideExampleGroup
end
class RuboCop::Cop::RSpec::LeakyConstantDeclaration < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::LetBeforeExamples < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::LetSetup < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::MatchArray < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::MessageChain < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::MessageExpectation < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::MessageSpies < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::MetadataStyle < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RSpec::Metadata
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::MissingExampleGroupArgument < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::MultipleDescribes < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::MultipleExpectations < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableMax
end
class RuboCop::Cop::RSpec::MultipleMemoizedHelpers < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableMax
  include RuboCop::Cop::RSpec::Variable
end
class RuboCop::Cop::RSpec::MultipleSubjects < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::NamedSubject < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::NestedGroups < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::ConfigurableMax
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::NoExpectationExample < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::AllowedPattern
  include RuboCop::Cop::RSpec::SkipOrPending
end
class RuboCop::Cop::RSpec::NotToNot < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::OverwritingSetup < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::Pending < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::SkipOrPending
end
class RuboCop::Cop::RSpec::PendingWithoutReason < RuboCop::Cop::RSpec::Base
end
module RuboCop::Cop::RSpec::InflectedHelper
  extend RuboCop::AST::NodePattern::Macros
  include RuboCop::RSpec::Language
end
module RuboCop::Cop::RSpec::ExplicitHelper
  extend RuboCop::AST::NodePattern::Macros
  include RuboCop::RSpec::Language
end
class RuboCop::Cop::RSpec::PredicateMatcher < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RSpec::ExplicitHelper
  include RuboCop::Cop::RSpec::InflectedHelper
end
class RuboCop::Cop::RSpec::ReceiveCounts < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ReceiveMessages < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::ReceiveNever < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::RedundantAround < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::RedundantPredicateMatcher < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::RemoveConst < RuboCop::Cop::RSpec::Base
  extend RuboCop::RSpec::Language::NodePattern
  include RuboCop::RSpec::Language
end
class RuboCop::Cop::RSpec::RepeatedDescription < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::RepeatedExample < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::RepeatedExampleGroupBody < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::SkipOrPending
end
class RuboCop::Cop::RSpec::RepeatedExampleGroupDescription < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::SkipOrPending
end
class RuboCop::Cop::RSpec::RepeatedIncludeExample < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::ReturnFromStub < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::ReturnFromStub::AndReturnCallCorrector
end
class RuboCop::Cop::RSpec::ReturnFromStub::BlockBodyCorrector
end
class RuboCop::Cop::RSpec::ScatteredLet < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::ScatteredSetup < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::SharedContext < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::SharedExamples < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::SharedExamples::SymbolChecker
end
class RuboCop::Cop::RSpec::SharedExamples::StringChecker
end
class RuboCop::Cop::RSpec::SingleArgumentMessageChain < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::RSpec::SkipBlockInsideExample < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::SortMetadata < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RSpec::Metadata
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::RSpec::SpecFilePathFormat < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::FileHelp
  include RuboCop::Cop::RSpec::Namespace
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::SpecFilePathSuffix < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::FileHelp
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::StubbedMock < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::SubjectDeclaration < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::SubjectStub < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::RSpec::TopLevelGroup
end
class RuboCop::Cop::RSpec::UnspecifiedException < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::VariableDefinition < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RSpec::InsideExampleGroup
  include RuboCop::Cop::RSpec::Variable
end
class RuboCop::Cop::RSpec::VariableName < RuboCop::Cop::RSpec::Base
  include RuboCop::Cop::AllowedPattern
  include RuboCop::Cop::ConfigurableNaming
  include RuboCop::Cop::RSpec::InsideExampleGroup
  include RuboCop::Cop::RSpec::Variable
end
class RuboCop::Cop::RSpec::VerifiedDoubleReference < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::RSpec::VerifiedDoubles < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::VoidExpect < RuboCop::Cop::RSpec::Base
end
class RuboCop::Cop::RSpec::Yield < RuboCop::Cop::RSpec::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::AST::Node < Parser::AST::Node
  include RuboCop::RSpec::Node
end
