# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tilt/all/tilt.rbi
#
# tilt-2.3.0

module Tilt
end
module Tilt::CompiledTemplates
end
class Tilt::Template
end
class Tilt::StaticTemplate < Tilt::Template
end
class Tilt::Pipeline < Tilt::Template
end
class Tilt::BaseMapping
end
class Tilt::Mapping < Tilt::BaseMapping
end
class Tilt::FinalizedMapping < Tilt::BaseMapping
end
class Tilt::Cache
end
