# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PrivateController`.
# Please instead update this file by running `bin/tapioca dsl PrivateController`.

class PrivateController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
