# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PublicController`.
# Please instead update this file by running `bin/tapioca dsl PublicController`.

class PublicController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
